export const INIT_IFRAME = 'INIT_IFRAME'
export const SET_COOKIE = 'SET_COOKIE'

export const GET_CURRENT_USER_VIA_JWT = 'GET_CURRENT_USER_VIA_JWT'

export const FETCH_CURRENT_USER = 'FETCH_CURRENT_USER'
export const FETCH_CURRENT_USER_PENDING = 'FETCH_CURRENT_USER_PENDING'
export const FETCH_CURRENT_USER_SUCCESS = 'FETCH_CURRENT_USER_SUCCESS'
export const FETCH_CURRENT_USER_FAILED = 'FETCH_CURRENT_USER_FAILED'
export const FETCH_CURRENT_USER_CANCELLED = 'FETCH_CURRENT_USER_CANCELLED'